### ISSUE TITLE
migrate to io.FS when Go 1.16 is out

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/fileglob#16]
I think we can migrate once its out... we would only need to write some sort of test fs... or wrap afero.FS in a io.FS... not sure yet... 

But the endgame IMHO is for the exposed API to use io.FS

**Comment by erikgeiser** [comment]
We should definitely do this. However, we have to keep in mind that that change would imply that `nfpm` and `goreleaser` also require Go 1.16 to build which may put off the Linux crowds with their slow distros. Personally, I can't be bothered with waiting for them to upgrade their stuff, but we should still keep that in mind.

**Comment by caarlos0** [comment]
hmm I think that's a non-issue for users using the goreleaser binaries... 

also, goreleaser always use the latest (I always update as soon as the new version is out), and this time, with m1 support coming on 1.16, it will not be different anyway... so.. IMHO... it should be fine 🤔

**Comment by erikgeiser** [comment]
Yeah the users are fine but I meant the contributors with Linux distributions that ship with compilers a few versions behind.

But, again, I'm with you and I think that's not really our problem.

**Comment by caarlos0** [comment]
done, since idk when
