### ISSUE TITLE
hi @caarlos0,

### ISSUE THREAD

**Issue by Intussenaa** [goreleaser/fileglob#38]
hi @caarlos0,

tried the branch:

```
      • building docker image     image=ghcr.io/dirien/minectl:v0.17.0-SNAPSHOT-arm64
      • running                   args=[. -t ghcr.io/dirien/minectl:v0.17.0-SNAPSHOT-arm64 --platform=linux/arm64/v8 --label=org.opencontainers.image.licenses=Apache-2.0 --label=org.opencontainers.image.description=minectl is a cli for creating Minecraft server on different cloud provider --label=org.opencontainers.image.created=2022-02-19T19:32:08Z --label=org.opencontainers.image.name=minectl --label=org.opencontainers.image.revision=203b4a73c0583299f48e3cd93eeeaf1e605a41a9 --label=org.opencontainers.image.version=v0.17.0-SNAPSHOT --label=org.opencontainers.image.source=https://github.com/dirien/minectl.git --label=io.artifacthub.package.maintainers=[{"name":"Engin Diri","email":"engin.diri@ediri.de"}] --label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/dirien/minectl/main/README.md --label=io.artifacthub.package.logo-url=https://dirien.github.io/minectl/img/minectl-logo.png --label=io.artifacthub.package.keywords=minecraft,server,cli --label=io.artifacthub.package.license=Apache-2.0] cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #1 [internal] load build definition from Dockerfile cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #1 transferring dockerfile: 200B 0.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #1 DONE 0.1s              cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #1 [internal] load build definition from Dockerfile cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #1 transferring dockerfile: 200B 0.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #1 DONE 0.0s              cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #2 [internal] load .dockerignore cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #2 transferring context: 2B 0.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #2 DONE 0.0s              cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #2 [internal] load .dockerignore cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #2 transferring context: 2B 0.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #2 DONE 0.1s              cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #3 [internal] load metadata for docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #3 DONE 0.1s              cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #5 [internal] load build context cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #3 [internal] load metadata for docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #3 DONE 0.2s              cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #5 [internal] load build context cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #5 ...                    cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #4 [1/2] FROM docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #4 resolve docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 0.3s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #4 DONE 0.4s              cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #5 [internal] load build context cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #5 ...                    cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #4 [1/2] FROM docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #4 resolve docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 0.4s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #4 DONE 0.4s              cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #5 [internal] load build context cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #5 transferring context: 43.10MB 4.8s cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #5 transferring context: 47.52MB 4.6s cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #5 transferring context: 54.86MB 5.8s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #5 DONE 5.9s              cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #4 [1/2] FROM docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #4 CACHED                 cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #5 transferring context: 56.38MB 5.5s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #5 DONE 5.6s              cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #4 [1/2] FROM docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #4 CACHED                 cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #6 [2/2] COPY minectl        /usr/bin/minectl cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #6 [2/2] COPY minectl        /usr/bin/minectl cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #6 DONE 0.6s              cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #6 DONE 0.7s              cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #7 exporting to oci image format cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #7 exporting layers       cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #7 exporting to oci image format cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #7 exporting layers       cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #7 exporting layers 5.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #7 exporting manifest sha256:f74fa96e1fff95378bc920b4a5c64bd0ef15c97569c3afa9725c497a8a4ab2ad 0.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #7 exporting config sha256:6221553a8f2c73981760fb82503d6a776d5b95fa9688516cd4a8702e0d3c89f6 0.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #7 sending tarball        cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #7 exporting layers 6.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #7 exporting manifest sha256:90effd0ea27381edc29fc7c6e75dc8025d316057cc3f9b8611fb40bbda435a21 0.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #7 exporting config sha256:002252dd992dfb81c1adc3537617473c7f0df064f304ba13314b04478c2a7f82 cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #7 exporting config sha256:002252dd992dfb81c1adc3537617473c7f0df064f304ba13314b04478c2a7f82 0.1s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #7 sending tarball        cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #7 sending tarball 2.7s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #7 DONE 7.8s              cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • unpacking ghcr.io/dirien/minectl:v0.17.0-SNAPSHOT-arm64 (sha256:f74fa96e1fff95378bc920b4a5c64bd0ef15c97569c3afa9725c497a8a4ab2ad)... cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • #7 sending tarball 2.9s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • #7 DONE 9.0s              cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • unpacking ghcr.io/dirien/minectl:v0.17.0-SNAPSHOT-amd64 (sha256:90effd0ea27381edc29fc7c6e75dc8025d316057cc3f9b8611fb40bbda435a21)... cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
         • done                      cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
         • done                      cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
```

```
nerdctl images
ghcr.io/dirien/minectl                                             v0.17.0-SNAPSHOT-amd64    90effd0ea273    3 minutes ago    linux/amd64    59.7 MiB
ghcr.io/dirien/minectl                                             v0.17.0-SNAPSHOT-arm64    f74fa96e1fff    3 minutes ago    linux/arm64    58.0 MiB
```

works fine for with `nerdctl` and rancher-desktop.

_Originally posted by @dirien in https://github.com/goreleaser/goreleaser/issues/2884#issuecomment-1046089641_

**Comment by Intussenaa** [comment]
> hi @caarlos0,
> 
> tried the branch:
> 
> ```
>       • building docker image     image=ghcr.io/dirien/minectl:v0.17.0-SNAPSHOT-arm64
>       • running                   args=[. -t ghcr.io/dirien/minectl:v0.17.0-SNAPSHOT-arm64 --platform=linux/arm64/v8 --label=org.opencontainers.image.licenses=Apache-2.0 --label=org.opencontainers.image.description=minectl is a cli for creating Minecraft server on different cloud provider --label=org.opencontainers.image.created=2022-02-19T19:32:08Z --label=org.opencontainers.image.name=minectl --label=org.opencontainers.image.revision=203b4a73c0583299f48e3cd93eeeaf1e605a41a9 --label=org.opencontainers.image.version=v0.17.0-SNAPSHOT --label=org.opencontainers.image.source=https://github.com/dirien/minectl.git --label=io.artifacthub.package.maintainers=[{"name":"Engin Diri","email":"engin.diri@ediri.de"}] --label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/dirien/minectl/main/README.md --label=io.artifacthub.package.logo-url=https://dirien.github.io/minectl/img/minectl-logo.png --label=io.artifacthub.package.keywords=minecraft,server,cli --label=io.artifacthub.package.license=Apache-2.0] cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #1 [internal] load build definition from Dockerfile cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #1 transferring dockerfile: 200B 0.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #1 DONE 0.1s              cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #1 [internal] load build definition from Dockerfile cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #1 transferring dockerfile: 200B 0.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #1 DONE 0.0s              cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #2 [internal] load .dockerignore cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #2 transferring context: 2B 0.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #2 DONE 0.0s              cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #2 [internal] load .dockerignore cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #2 transferring context: 2B 0.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #2 DONE 0.1s              cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #3 [internal] load metadata for docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #3 DONE 0.1s              cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #5 [internal] load build context cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #3 [internal] load metadata for docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #3 DONE 0.2s              cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #5 [internal] load build context cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #5 ...                    cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #4 [1/2] FROM docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #4 resolve docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 0.3s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #4 DONE 0.4s              cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #5 [internal] load build context cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #5 ...                    cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #4 [1/2] FROM docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #4 resolve docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 0.4s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #4 DONE 0.4s              cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #5 [internal] load build context cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #5 transferring context: 43.10MB 4.8s cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #5 transferring context: 47.52MB 4.6s cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #5 transferring context: 54.86MB 5.8s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #5 DONE 5.9s              cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #4 [1/2] FROM docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #4 CACHED                 cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #5 transferring context: 56.38MB 5.5s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #5 DONE 5.6s              cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #4 [1/2] FROM docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #4 CACHED                 cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #6 [2/2] COPY minectl        /usr/bin/minectl cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #6 [2/2] COPY minectl        /usr/bin/minectl cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #6 DONE 0.6s              cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #6 DONE 0.7s              cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #7 exporting to oci image format cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #7 exporting layers       cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          •                           cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #7 exporting to oci image format cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #7 exporting layers       cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #7 exporting layers 5.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #7 exporting manifest sha256:f74fa96e1fff95378bc920b4a5c64bd0ef15c97569c3afa9725c497a8a4ab2ad 0.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #7 exporting config sha256:6221553a8f2c73981760fb82503d6a776d5b95fa9688516cd4a8702e0d3c89f6 0.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #7 sending tarball        cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #7 exporting layers 6.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #7 exporting manifest sha256:90effd0ea27381edc29fc7c6e75dc8025d316057cc3f9b8611fb40bbda435a21 0.0s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #7 exporting config sha256:002252dd992dfb81c1adc3537617473c7f0df064f304ba13314b04478c2a7f82 cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #7 exporting config sha256:002252dd992dfb81c1adc3537617473c7f0df064f304ba13314b04478c2a7f82 0.1s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #7 sending tarball        cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #7 sending tarball 2.7s done cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #7 DONE 7.8s              cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • unpacking ghcr.io/dirien/minectl:v0.17.0-SNAPSHOT-arm64 (sha256:f74fa96e1fff95378bc920b4a5c64bd0ef15c97569c3afa9725c497a8a4ab2ad)... cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • #7 sending tarball 2.9s done cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • #7 DONE 9.0s              cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • unpacking ghcr.io/dirien/minectl:v0.17.0-SNAPSHOT-amd64 (sha256:90effd0ea27381edc29fc7c6e75dc8025d316057cc3f9b8611fb40bbda435a21)... cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
>          • done                      cmd=[nerdctl build] cwd=dist/goreleaserdocker177255777
>          • done                      cmd=[nerdctl build] cwd=dist/goreleaserdocker2008917009
> ```
> 
> ```
> nerdctl images
> ghcr.io/dirien/minectl                                             v0.17.0-SNAPSHOT-amd64    90effd0ea273    3 minutes ago    linux/amd64    59.7 MiB
> ghcr.io/dirien/minectl                                             v0.17.0-SNAPSHOT-arm64    f74fa96e1fff    3 minutes ago    linux/arm64    58.0 MiB
> ```
> 
> works fine for with `nerdctl` and rancher-desktop.
> 
> _Originally posted by @dirien in [goreleaser/goreleaser#2884 (comment)](https://github.com/goreleaser/goreleaser/pull/2884#issuecomment-1046089641)_

**Comment by caarlos0** [comment]
wtf
